cmake_minimum_required(VERSION 3.25)
project(prog2001 C)

set(CMAKE_C_STANDARD 11)

add_executable(Bai1 Chapter01/ExOne/src/1.c)
add_executable(Bai2 Chapter01/ExTwo/src/2.c)
add_executable(Bai3 Chapter01/ExThree/src/3.c)
add_executable(Bai4 Chapter01/ExFour/src/4.c)
add_executable(Bai5 Chapter01/ExFive/src/5.c)
add_executable(Bai6 Chapter01/ExSix/src/6.c)
add_executable(Bai7 Chapter01/ExSeven/src/7.c)